### ISSUE TITLE
Erratic PredAI load predictions

### ISSUE THREAD

**Issue by pbyrne-ms** [springfall2008/predai#7]
Erratic PredAI load predictions

PredAI Version: 1.1.7
PredBAT Version: 7.17.2
HA Version: 2024.4.3

For about a week now, my PredAI predicted load entity 'sensor.givtcp1_chxxxxxxxx_load_energy_today_kwh_prediction' has been forecasting extremely large load values. And then, even more erratically, goes back to normal after a few hours.
By Erratic, usually the prediction adds 800kWh-ish to the load..
 
 
YAML file is the most simple example possible

```
update_every: 30
sensors:
  - name: sensor.givtcp_chxxxxxx_load_energy_today_kwh
    #subtract: sensor.car_charger_energy_today
    days: 14
    incrementing: True
    reset_daily: True
    interval: 30
    units: kWh
    future_periods: 96
    #database: True
```

Screenshots:
![image](https://github.com/springfall2008/predai/assets/33572035/8bd1fdb5-0843-4533-bcce-69c8d6ffac53)

Any suggestions? or spot anything wrong?
